// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ1O4y64-y9AQniM6QGCQw6dYxU0n40KY',
    appId: '1:925908168972:web:356e0f3a879b7b6f3d1929',
    messagingSenderId: '925908168972',
    projectId: 'go-hurghada-ffab9',
    authDomain: 'go-hurghada-ffab9.firebaseapp.com',
    storageBucket: 'go-hurghada-ffab9.firebasestorage.app',
    measurementId: 'G-VSC93SVKT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-wXV_u4LV7B20w4eCqhQeouuqcjp3_A4',
    appId: '1:925908168972:android:1e7195909f8ac0b93d1929',
    messagingSenderId: '925908168972',
    projectId: 'go-hurghada-ffab9',
    storageBucket: 'go-hurghada-ffab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4mBp6ek1SYNy5AzC2-dIhcNTK8S8FEJw',
    appId: '1:925908168972:ios:96a76255c0d109f43d1929',
    messagingSenderId: '925908168972',
    projectId: 'go-hurghada-ffab9',
    storageBucket: 'go-hurghada-ffab9.firebasestorage.app',
    iosClientId: '925908168972-sb1r5mfj7oo8am1bcjl5c4f6ad3fq7t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.goHurghada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ1O4y64-y9AQniM6QGCQw6dYxU0n40KY',
    appId: '1:925908168972:web:36957063e1e0e0913d1929',
    messagingSenderId: '925908168972',
    projectId: 'go-hurghada-ffab9',
    authDomain: 'go-hurghada-ffab9.firebaseapp.com',
    storageBucket: 'go-hurghada-ffab9.firebasestorage.app',
    measurementId: 'G-EHCR2DCSJX',
  );
}
